name: 'Experiment Runner. Seed build populating cache'
description: 'Runs experiments with various Gradle caching strategies.'

inputs:
  task:
    description: 'The Gradle task to be executed.'
    required: true
  variant:
    description: 'The variant to be used, representing the branch.'
    required: true
  variant-prefix:
    description: 'Prefix for the variant used in tagging.'
    required: true
  experiment-id:
    description: 'Unique identifier for the experiment.'
    required: true
  api-key:
    description: 'API key for accessing Develocity or related services.'
    required: true
  repository:
    description: 'GitHub repository to check out.'
    required: true
  jdk_version:
    description: 'Java version to use (default is 17).'
    required: false
    default: 17
  jdk_vendor:
    description: 'JDK vendor to use (default is zulu).'
    required: false
    default: 'zulu'
  mode:
    description: 'Mode of execution relative to caching.'
    required: true
  extra-args:
    description: 'Extra arguments to pass to the Gradle command.'
    required: true
  cache-exclude-script:
    description: 'Script for excluding specific caches.'
    required: false
  rl-actions:
    description: 'RL-generated action parameters (JSON string)'
    required: false
    default: '{}'

outputs:
  cache-excludes:
    description: 'Cache exclusion logic output.'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.variant }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.jdk_vendor }}
        java-version: ${{ inputs.jdk_version }}

    - name: Set Gradle Cache Excludes
      id: set-cache-excludes
      run: |
        BUILD_CACHE_ENTRY="caches/build-cache-1"
        TRANSFORM_CACHE_ENTRY="caches/**/transforms"
        MODULES_CACHE_ENTRY="caches/modules-*/*"
        JAR_CACHE_ENTRY="caches/jars-*/*"
        echo "GRADLE_HOME_CACHE_EXCLUDES=$BUILD_CACHE_ENTRY" >> $GITHUB_ENV
        echo "cache-excludes=$GRADLE_HOME_CACHE_EXCLUDES" >> $GITHUB_ENV
      shell: bash

    - name: Setup Gradle
      if: github.event.inputs.mode != 'no caching'
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-overwrite-existing: true
        add-job-summary: 'never'
        gradle-home-cache-excludes: ${{ env.GRADLE_HOME_CACHE_EXCLUDES }}
      env:
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: ${{ inputs.repository }}-${{ inputs.task }}-${{ inputs.variant }}

    - name: Apply RL Optimizations to Gradle Properties
      id: apply-rl-optimizations
      run: |
        echo "RL Actions: ${{ fromJson(inputs.rl-actions) }}"
        echo "Max Workers: ${{ fromJson(inputs.rl-actions).max_workers }}"
        echo "Gradle Heap: ${{ fromJson(inputs.rl-actions).gradle_heap_gb }}"
        echo "Kotlin Heap: ${{ fromJson(inputs.rl-actions).kotlin_heap_gb }}"
        # Create or update gradle.properties with RL optimizations
        GRADLE_PROPS_FILE="gradle.properties"
        
        # Update org.gradle.jvmargs with gradle heap
        if grep -q "org.gradle.jvmargs" "$GRADLE_PROPS_FILE"; then
          # Replace existing values only in org.gradle.jvmargs line
          sed -i "/org.gradle.jvmargs/s/-Xmx[0-9]*[gG]/-Xmx${{ fromJson(inputs.rl-actions).gradle_heap_gb }}g/g" "$GRADLE_PROPS_FILE"
          sed -i "/org.gradle.jvmargs/s/-Xms[0-9]*[gG]/-Xms${{ fromJson(inputs.rl-actions).gradle_heap_gb }}g/g" "$GRADLE_PROPS_FILE"
        else
          # Add org.gradle.jvmargs if it doesn't exist
          echo "org.gradle.jvmargs=-Xmx${{ fromJson(inputs.rl-actions).gradle_heap_gb }}g " >> "$GRADLE_PROPS_FILE"
        fi
        
        # Update org.gradle.workers.max with max workers
        if grep -q "org.gradle.workers.max" "$GRADLE_PROPS_FILE"; then
          # Update existing org.gradle.workers.max
          sed -i "s/org.gradle.workers.max=[0-9]*/org.gradle.workers.max=${{ fromJson(inputs.rl-actions).max_workers }}/g" "$GRADLE_PROPS_FILE"
        else
          # Add org.gradle.workers.max if it doesn't exist
          echo "org.gradle.workers.max=${{ fromJson(inputs.rl-actions).max_workers }}" >> "$GRADLE_PROPS_FILE"
        fi
        
        # Update kotlin.daemon.jvmargs with kotlin heap
        if grep -q "kotlin.daemon.jvmargs" "$GRADLE_PROPS_FILE"; then
          # Replace existing values only in kotlin.daemon.jvmargs line
          sed -i "/kotlin.daemon.jvmargs/s/-Xmx[0-9]*[gG]/-Xmx${{ fromJson(inputs.rl-actions).kotlin_heap_gb }}g/g" "$GRADLE_PROPS_FILE"
          sed -i "/kotlin.daemon.jvmargs/s/-Xms[0-9]*[gG]/-Xms${{ fromJson(inputs.rl-actions).kotlin_heap_gb }}g/g" "$GRADLE_PROPS_FILE"
        else
          # Add kotlin.daemon.jvmargs if it doesn't exist
          echo "kotlin.daemon.jvmargs=-Xmx${{ fromJson(inputs.rl-actions).kotlin_heap_gb }}g " >> "$GRADLE_PROPS_FILE"
        fi
        
        echo "Updated gradle.properties with RL optimizations:"
        cat "$GRADLE_PROPS_FILE"
      shell: bash

    - name: Execute Gradle Build
      id: gradle-build
      run: |
        echo "11"
        ls
        experiment_id_value="${{ inputs.experiment-id }}_W${{ fromJson(inputs.rl-actions).max_workers }}_G${{ fromJson(inputs.rl-actions).gradle_heap_gb }}_K${{ fromJson(inputs.rl-actions).kotlin_heap_gb }}"
        ./gradlew ${{ inputs.task }} ${{ inputs.extra-args }} \
          -Dscan.tag.seed_${{ inputs.variant-prefix }}${{ inputs.variant }} \
          -Dscan.tag.seed-"${{ inputs.mode }}" \
          -Dscan.tag.seed \
          -Dscan.tag.seed_"$experiment_id_value" \
          -Dscan.tag.seed_${{ inputs.experiment-id }}
      shell: bash
      env:
        DEVELOCITY_ACCESS_KEY: ${{ inputs.api-key }}


    - name: Archive Gradle User Home
      uses: actions/upload-artifact@v4
      with:
        name: gradle-user-home-${{ inputs.variant-prefix }}${{ inputs.variant }}
        path: ${{ env.GRADLE_USER_HOME }}
        retention-days: 1

    - name: Archive Project Workspace
      uses: actions/upload-artifact@v4
      with:
        name: project-workspace-${{ inputs.variant-prefix }}${{ inputs.variant }}
        path: ${{ github.workspace }}
        retention-days: 1

    - name: Finalize Step
      uses: actions/checkout@v4
